### ISSUE TITLE
estimate radius while fixing the center of origin 

### ISSUE THREAD

**Issue by Young-JZ-Wang** [cjekel/cjekel.github.io#2]
Hi there,

Thanks for this awesome script. I wonder if it's possible to formulate the script into estimating radius while fixing the center of origin?

**Comment by cjekel** [comment]
I haven't really tested this, but I think the following should do the trick.
```python
def calc_r(spX, spY, spZ):
    #   Assemble the A matrix
    spX = np.array(spX)
    spY = np.array(spY)
    spZ = np.array(spZ)
    A = np.ones((len(spX),1))

    #   Assemble the f matrix
    f = np.zeros((len(spX),1))
    f[:, 0] = (spX*spX) + (spY*spY) + (spZ*spZ) + (x0*x0) + (y0*y0) + (z0*z0)
    f[:, 0] -= 2.0*spX*x0 + 2.0*spY*y0 + 2.0*spZ*z0
    C, residules, rank, singval = np.linalg.lstsq(A,f)

    #   solve for the radius
    radius = np.sqrt(C[0])

    return radius
```

**Comment by Young-JZ-Wang** [comment]
hi @cjekel thank you for the quick reply. I tried this and it works

`

class sphere_fit:
    def __init__(self, pts, centre = None, fixed_origin = True):

        self.x, self.y, self.z = zip(*pts)
        self.fixed_origin = fixed_origin

        if fixed_origin:
            self.centre = centre
            self.x = np.array(self.x) - self.centre[0]
            self.y = np.array(self.y) - self.centre[1]
            self.z = np.array(self.z) - self.centre[2]

        else:
            self.x = np.array(self.x)
            self.y = np.array(self.y)
            self.z = np.array(self.z)

        self.A = self.form_A()
        self.B = self.form_B()

        self.radius, self.origin = self.cal_sphere()

    def form_A(self):
        A = np.zeros((len(self.x), 4))
        A[:, 0] = self.x * 2
        A[:, 1] = self.y * 2
        A[:, 2] = self.z * 2
        A[:, 3] = 1

        return A

    def form_B(self):
        #   Assemble the f matrix
        B = np.zeros((len(self.x), 1))
        B[:, 0] = (self.x * self.x) + (self.y * self.y) + (self.z * self.z)
        return B

    #
    def cal_sphere(self):
        c, residules, _, _ = np.linalg.lstsq(self.A, self.f, rcond=None)
        radius = np.sqrt((c[0] * c[0]) + (c[1] * c[1]) + (c[2] * c[2]) + c[3])
        if self.fixed_origin:
            origin = (c[0]+self.centre[0], c[1]+self.centre[1], c[2]+self.centre[2])
        else:
            origin = (c[0], c[1], c[2])

        return radius, origin

    def plot(self, ax):
        x0, y0, z0 = self.origin[0], self.origin[1], self.origin[2]

        u, v = np.mgrid[0:2 * np.pi:20j, 0:np.pi:10j]
        x = np.cos(u) * np.sin(v) * self.radius
        y = np.sin(u) * np.sin(v) * self.radius
        z = np.cos(v) * self.radius
        if self.fixed_origin:

            x = x + x0 - self.centre[0]
            y = y + y0 - self.centre[1]
            z = z + z0 - self.centre[2]
        else:
            x = x + x0
            y = y + y0
            z = z + z0

        ax.scatter(self.x, self.y, self.z, zdir='z', s=0.1, c='b',alpha=0.3, rasterized=True)
        ax.plot_wireframe(x, y, z, color="r",)
        origin = np.asarray(self.origin).flatten()
        ax.set_title('radius = %.2f \n origin(x,y,z) is %s' % (self.radius, origin))
        return ax
`
